### ISSUE TITLE
$ref '/definitions/HProperties' in 'vscode://schemas/settings/user' can not be resolved.

### ISSUE THREAD

**Issue by aeschli** [HookyQR/VSCodeBeautify#266]
See https://github.com/Microsoft/vscode/issues/57460:

ll of a sudden I am getting this warning on all of my settings.json files.

`$ref '/definitions/HProperties' in 'vscode://schemas/settings/user' can not be resolved.`
This occurs even in latest insider build. Line 1 at { in the Settings.json

**Comment by aeschli** [comment]
I reproduce by installing the latest version of VSCodeBeautify.

Likely caused by this line: https://github.com/HookyQR/VSCodeBeautify/blob/97790c4da01aad6d5bab8562c0ffdd3ddd16bd7d/package.json#L164

I advise against to use of $ref in settings definition. Please keep the settings simple.

**Comment by coder3101** [comment]
@aeschli Thank you for finding the issue. Meanwhile I will disable this extension till this issue is resolved.

**Comment by demisx** [comment]
Same here. Disabling "Beautify" extension made the error go away. Hopefully, it will be resolved soon.

**Comment by irishquinn** [comment]
Instead of disabling the extension completely, you could just add this to your user settings - 

I just removed the `json` and `jsonc` from the file types settings in vscode...then the error went away.
` {
    "js": {
      "type": [
        "javascript",
         "json",      // remove this line
         "jsonc"    // and remove this line (i removed it because i don't ever use this file extension)
      ],
      "filename": [
        ".jshintrc",
        ".jsbeautifyrc"
      ]
    },
    "css": [
      "css",
      "scss"
    ],
    "html": [
      "htm",
      "html"
    ]
  }`

then save your settings and the problem message goes away...

**Comment by benjamenhogben** [comment]
[Above solution](https://github.com/HookyQR/VSCodeBeautify/issues/266#issuecomment-418206137) didn't fix for me, neither did removing all custom Beautify settings including .jsbeautifyrc

**Comment by changeling** [comment]
Bump.

Same issue.

**Comment by webia1** [comment]
same here & today,..

**Comment by syedsimanta03** [comment]
Same here. Please fix Asap..................................

**Comment by HookyQR** [comment]
@aeschli you advised against loading remote schema via $ref. I can see now that, despite following the spec when loading a schema for a file type, it just doesn't play nice inside the VS Code settings file. I'll simply remove all hints, as including them all nicely just won't be supported by the controlling system.

**Comment by HookyQR** [comment]
Pull requests are nice BTW people. But don't worry, I killed it all off.
